# Generated by Django 5.2.6 on 2025-09-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bibiographie',
            new_name='biographie',
        ),
        migrations.AddField(
            model_name='customuser',
            name='localisation',
            field=models.CharField(blank=True, default='brazzaville', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiirepersonnel',
            field=models.CharField(blank=True, default='full', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-stack', 'Full-stack'), ('Mobile', 'Mobile'), ('Cloud & DevOps', 'Cloud & DevOps'), ('IA', 'Intelligence Artificielle'), ('Réseau', 'Réseau'), ('Système', 'Système'), ('Unix', 'Unix'), ('base de données', 'Base de données'), ('Sécurité', 'Sécurité'), ('Autre', 'Autre')], max_length=500),
        ),
    ]
