# Generated by Django 5.2.6 on 2025-09-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_bibiographie_customuser_biographie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tiirepersonnel',
            new_name='titrepersonnel',
        ),
    ]
