# Generated by Django 5.2.6 on 2025-09-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tiirepersonnel_customuser_titrepersonnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='location',
            new_name='localisation',
        ),
    ]
