# Generated by Django 5.2.6 on 2025-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='type',
            field=models.CharField(choices=[('Diplôme', 'Diplôme'), ('Certificat', 'Certificat'), ('Formation_suivie_(non certifiée)', 'Formation suivie (non certifiée)'), ('Formation_suivie_(certificat en attente)', 'Formation suivie (certificat en attente)'), ('Formation en auto-apprentissage', 'Formation en auto-apprentissage'), ('Autre', 'Autre')], default='Diplôme', max_length=50),
        ),
    ]
